import type { Metadata } from "next";
import Header from "../components/organisms/Header";
import Navigation from "../components/organisms/Navigation";
import "./globals.css";
import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Todo-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={openSans.variable}>
      <body>
        <Header />
        <Navigation />
        <main>{children}</main>
      </body>
    </html>
  );
}
